= PCF Environment Access

== Account set up and Pre-work

. If you do not have an account yet, please log into Apps Manager with MyID

. Navigate in a web browser to https://apps.system.pivotalpoc.hosts.disney.pvt

. Click the MyID link and log-in using SSO.  The interface will show you do not have ORG permission. Take a screenshot.

. Send an email to the instructor requesting access to a developer space with a screenshot of the Apps Manager interface, be sure to include your BU (ABC, Parks, Studios, etc)


== Target the Environment

. If you haven't already, download the latest release of the Cloud Foundry CLI from https://github.com/cloudfoundry/cli/releases for your operating system and install it.

. Set the API target for the CLI: (set appropriate end point for your environment)
+
----
$ cf login -a api.system.pivotalpoc.hosts.disney.pvt -sso --skip-ssl-validation
----

. You will be promoted for a one time passcode from a URL; navigate to it in your browser

. Enter the code at the prompt

. Verify target of your environment
+
----
$ cf target
----

== Installing CLI via Apps Manager UI

. An alternative to installing the CF CLI is via your PCF Apps Manager interface.

. Navigate in a web browser to https://apps.system.pivotalpoc.hosts.disney.pvt

. Login to the interface with MyID

. Click the 'Tools' link, and download the CLI matching your operating system

. Install the CLI
